### ISSUE TITLE
Mediplay Staff Editor - Missing User Role Editors

### ISSUE THREAD

**Issue by kipp-qstart** [QStart-Labs/mediplay#2]
/mediplay/admin/portal/editor

I don't see the Editors for these:

Account Home - Administrator (User Role) "quick link" editor
Administration Intro (User Role)
Administrator - Group (User Role) "quick link" editor
Groups Intro (User Role)

**Comment by kipp-qstart** [comment]
I see them now (helps if you login on Test instead of Live).....

**Comment by IanShortridge** [comment]
I did it!

**Comment by kipp-qstart** [comment]
Ha! Yeah I was logged-in on Live and didn't notice at first.....
