### ISSUE TITLE
Groups page (User Role) - Player Name and Location

### ISSUE THREAD

**Issue by kipp-qstart** [QStart-Labs/mediplay#3]
/mediplay/subscriber/userAdmin/userGroups

I think you are using the "Mediplay" player name and "Mediplay" location name on this page
Use the Subscriber player name and the actual location address (address, city, state, zip)

Also can we put the Player Name and Location in a table (formatted like the other tables)?

**Comment by IanShortridge** [comment]
Yea and I'll put them in tables to match how the Locations page looks.

**Comment by kipp-qstart** [comment]
Looks good.
